---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: sp-bt-ex
  name: sp-bt-ex-cr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sp-bt-ex
    spec:
      containers:
      - image: chandar19/spring-boot-example:${GIT_COMMIT_HASH}
        name: sp-bt-ex
        ports:
        - name: sp-bt-ex
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sp-bt-ex
  name: sp-bt-ex
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    name: sp-bt-ex
